services:
  - type: web
    plan: free
    name: digital-rename-bot
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg fonts-dejavu-core
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_NAME
        value: VideoThumbMark
      - key: ADMIN
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: WATERMARK_TEXT
        value: "@Coursesbuying"
      - key: WATERMARK_POSITION
        value: "bottom-right"
      - key: RKN_PIC
        sync: false

