services:
  - type: web
    plan: free
    name: digital-rename-bot
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_NAME
        value: VideoThumbMark
      - key: ADMIN
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: WATERMARK_TEXT
        value: "@Coursesbuying"
      - key: WATERMARK_POSITION
        value: "scroll-lr-center"
      - key: WATERMARK_FONTFILE
        value: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
      - key: RKN_PIC
        sync: false

